<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/deepak/gitrepos/buildkit/build/d5x/sites/default/files/civicrm/ext/uk.co.mountev.cartcheckout/xml/schema/CRM/Cartcheckout/CartItem.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cbcbd62994f6236b4b27d48313c3c3b6)
 */

/**
 * Database access object for the CartItem entity.
 */
class CRM_Cartcheckout_DAO_CartItem extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_cart_item';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique CartItem ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Cart
   *
   * @var int
   */
  public $cart_id;

  /**
   * @var string
   */
  public $entity_table;

  /**
   * @var int
   */
  public $entity_id;

  /**
   * FK to civicrm_price_field_value Table
   *
   * @var int
   */
  public $pfv_id;

  /**
   * Whether the item was included in final checkout
   *
   * @var bool
   */
  public $is_checkedout;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_cart_item';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'cart_id', 'civicrm_cart', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'pfv_id', 'civicrm_price_field_value', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('Unique CartItem ID'),
          'required' => TRUE,
          'where' => 'civicrm_cart_item.id',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
        ],
        'cart_id' => [
          'name' => 'cart_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('FK to Cart'),
          'required' => TRUE,
          'where' => 'civicrm_cart_item.cart_id',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
          'FKClassName' => 'CRM_Cartcheckout_DAO_Cart',
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Cartcheckout_ExtensionUtil::ts('Entity Table'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'where' => 'civicrm_cart_item.entity_table',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Cartcheckout_ExtensionUtil::ts('Entity ID'),
          'required' => TRUE,
          'where' => 'civicrm_cart_item.entity_id',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
        ],
        'pfv_id' => [
          'name' => 'pfv_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('FK to civicrm_price_field_value Table'),
          'where' => 'civicrm_cart_item.pfv_id',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
          'FKClassName' => 'CRM_Price_DAO_PriceFieldValue',
        ],
        'is_checkedout' => [
          'name' => 'is_checkedout',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Cartcheckout_ExtensionUtil::ts('Is Checked Out?'),
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('Whether the item was included in final checkout'),
          'where' => 'civicrm_cart_item.is_checkedout',
          'default' => '0',
          'table_name' => 'civicrm_cart_item',
          'entity' => 'CartItem',
          'bao' => 'CRM_Cartcheckout_DAO_CartItem',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'cart_item', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'cart_item', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
