<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/deepak/gitrepos/buildkit/build/d5x/sites/default/files/civicrm/ext/uk.co.mountev.cartcheckout/xml/schema/CRM/Cartcheckout/PurchasedPapers.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:11680c7314b4e422dfa29511f7d45f1a)
 */

/**
 * Database access object for the PurchasedPapers entity.
 */
class CRM_Cartcheckout_DAO_PurchasedPapers extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_purchased_papers';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique PurchasedPapers ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * FK to Contribution
   *
   * @var int
   */
  public $contribution_id;

  /**
   * @var string
   */
  public $paper_number;

  /**
   * @var string
   */
  public $paper;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_purchased_papers';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contribution_id', 'civicrm_contribution', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('Unique PurchasedPapers ID'),
          'required' => TRUE,
          'where' => 'civicrm_purchased_papers.id',
          'table_name' => 'civicrm_purchased_papers',
          'entity' => 'PurchasedPapers',
          'bao' => 'CRM_Cartcheckout_DAO_PurchasedPapers',
          'localizable' => 0,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_purchased_papers.contact_id',
          'table_name' => 'civicrm_purchased_papers',
          'entity' => 'PurchasedPapers',
          'bao' => 'CRM_Cartcheckout_DAO_PurchasedPapers',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ],
        'contribution_id' => [
          'name' => 'contribution_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Cartcheckout_ExtensionUtil::ts('FK to Contribution'),
          'where' => 'civicrm_purchased_papers.contribution_id',
          'table_name' => 'civicrm_purchased_papers',
          'entity' => 'PurchasedPapers',
          'bao' => 'CRM_Cartcheckout_DAO_PurchasedPapers',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contribute_DAO_Contribution',
        ],
        'paper_number' => [
          'name' => 'paper_number',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Cartcheckout_ExtensionUtil::ts('Paper Number'),
          'required' => TRUE,
          'maxlength' => 16,
          'size' => CRM_Utils_Type::TWELVE,
          'where' => 'civicrm_purchased_papers.paper_number',
          'table_name' => 'civicrm_purchased_papers',
          'entity' => 'PurchasedPapers',
          'bao' => 'CRM_Cartcheckout_DAO_PurchasedPapers',
          'localizable' => 0,
        ],
        'paper' => [
          'name' => 'paper',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Cartcheckout_ExtensionUtil::ts('Paper'),
          'maxlength' => 512,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_purchased_papers.paper',
          'table_name' => 'civicrm_purchased_papers',
          'entity' => 'PurchasedPapers',
          'bao' => 'CRM_Cartcheckout_DAO_PurchasedPapers',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'purchased_papers', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'purchased_papers', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
