-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_cart_item`;
DROP TABLE IF EXISTS `civicrm_cart`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_cart
-- *
-- *******************************************************/
CREATE TABLE `civicrm_cart` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique Cart ID',
     `user_id` int unsigned    COMMENT 'FK to Contact',
     `is_completed` tinyint   DEFAULT 0 ,
     `payment_id` int unsigned    COMMENT 'FK to checked out Contribution' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_cart_user_id FOREIGN KEY (`user_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,          CONSTRAINT FK_civicrm_cart_payment_id FOREIGN KEY (`payment_id`) REFERENCES `civicrm_contribution`(`id`) ON DELETE SET NULL  
)    ;

-- /*******************************************************
-- *
-- * civicrm_cart_item
-- *
-- *******************************************************/
CREATE TABLE `civicrm_cart_item` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique CartItem ID',
     `cart_id` int unsigned NOT NULL   COMMENT 'FK to Cart',
     `entity_table` varchar(64) NOT NULL   ,
     `entity_id` int unsigned NOT NULL   ,
     `pfv_id` int unsigned    COMMENT 'FK to civicrm_price_field_value Table',
     `is_checkedout` tinyint   DEFAULT 0 COMMENT 'Whether the item was included in final checkout' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_cart_item_cart_id FOREIGN KEY (`cart_id`) REFERENCES `civicrm_cart`(`id`) ON DELETE CASCADE,          CONSTRAINT FK_civicrm_cart_item_pfv_id FOREIGN KEY (`pfv_id`) REFERENCES `civicrm_price_field_value`(`id`) ON DELETE SET NULL  
)    ;

 